[package]
name = "filter-repo-rs"
version = "0.0.1"
edition = "2021"
description = "Prototype of git-filter-repo in Rust: minimal export->filter->import pipeline"
license = "MIT"

[dependencies]
regex = "1"

[lib]
name = "filter_repo_rs"
path = "src/lib.rs"

[dev-dependencies]
tempfile = "3.8"

